name: qtism_math
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  speech_to_text: ^7.0.0
  chat_gpt_sdk: ^3.1.4
  dash_chat_2: ^0.0.21
  math_expressions: ^2.7.0
  async: ^2.12.0
  material_color_utilities: ^0.11.1
  permission_handler: ^11.3.0
  flutter_markdown: ^0.7.1
  http: ^1.1.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  fake_async: ^1.3.2
  leak_tracker: ^10.0.8
  vm_service: 14.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env