// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQIDJ4CsermJFWwJo-Qomty_WXOTcwIXw',
    appId: '1:142934592330:web:08f1ffdd09e65ed69e0fb3',
    messagingSenderId: '142934592330',
    projectId: 'qtism-math',
    authDomain: 'qtism-math.firebaseapp.com',
    storageBucket: 'qtism-math.firebasestorage.app',
    measurementId: 'G-413GDPQF9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0qpAJ3kSySckMNpd3RN4m01pw0fndZtQ',
    appId: '1:142934592330:android:ac349686216965ac9e0fb3',
    messagingSenderId: '142934592330',
    projectId: 'qtism-math',
    storageBucket: 'qtism-math.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCbfTiz2mObvzoyCZBeA66d2s-HH9P3bc',
    appId: '1:142934592330:ios:8b9f9b4526b21e489e0fb3',
    messagingSenderId: '142934592330',
    projectId: 'qtism-math',
    storageBucket: 'qtism-math.firebasestorage.app',
    iosBundleId: 'com.example.qtismMath',
  );
}
